export * from './IQuestionRepository'
export * from './IQuizRepository'
export * from './ISubmissionRepository'
export * from './IUserTokenRepository'
export * from './IUsersRepository'
export * from './IActivateCodeRepository'